# -*- coding: utf-8 -*-
"""advecciondif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Qu2nu4JNVG2fe7bjEIq1dqRR5oktJlQ

# DRIVE
"""

# Commented out IPython magic to ensure Python compatibility.
#Your google drive is made accesible to Colab.
try:
    from google.colab import drive
    drive.mount('/content/drive/')
    #%cd /content/drive/MyDrive/tfg_guillermo/code/Transporte lineal 2 (sin model.fit).ipynb
#     %cd /content/drive/MyDrive/TFGs_TFM_2023-2024/TFGs_propuestas_Física/Guillermo_Gracia_Rebullida/tfg_guillermo/code
#     %ls -lht
    # To import own packages set local path in packages syspath
    import sys
    sys.path.insert(0,"./")
except ImportError:
    print("You are not in google.colab!!")
    import os
    # List files in the current working directory
    files_in_directory = os.listdir()
    for file in files_in_directory:
        print(file)

"""# Librerias"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Dense
import imageio.v2 as imageio

"""# Condiciones iniciales"""

#condiciones del problema

v=5.0
v_tensor=tf.constant([[5.0]],dtype=tf.float32)
p0=1.0
c=1.0
alpha=10.0
alpha_tensor=tf.constant([[10.0]],dtype=tf.float32)
kt=10.0
R=0.01
h=0.01
C=0.001
x0=250.0
Tinf=300.0


#ecuación

# dT\dt +v dT\dx=alfa d2T/dx2-R(T-Tinf)
# T0(x)=300+100exp(-C(x-x0)^2) independientemente del tiempo

def T0(x):
    return 300.0+100*np.exp(-C*(x-x0)**2)

def T_real(x,t):
    return 300.0 + 100/np.sqrt(1+4*C*alpha*t)*np.exp(-C*(x-x0-v*t)**2/(1+4*C*alpha*t))*np.exp(-R*t)

"""# Dominio"""

#dominio

xmin=0
xmax=1000
tmin=0
tmax=100
n_train=5000
n_train0=10000
n_border=100
N_STEPS=10000
log_each=500

"""# Entrenamiento"""

#parametros redes
nInput=2
nOutput=1
nhiddenlayers=5
nnhiddenlayers=125

#hiperparametros
lr=0.001

#nn

model=Sequential()
model.add(Input(shape=(nInput,)))
for i in range(0,nhiddenlayers):
  model.add(Dense(nnhiddenlayers,activation='sigmoid'))
model.add(Dense(1,activation=None))

# Metrica, perdida y optimizador
loss = tf.keras.losses.MeanSquaredError()
metrics = tf.keras.metrics.MeanSquaredError()
optimizer = tf.keras.optimizers.Adam(lr)

model.compile(loss=loss,optimizer=optimizer,metrics=[metrics])

ceros = tf.zeros(n_border,dtype=tf.float32)
unos = tf.ones(n_border,dtype=tf.float32)
miles=1000*unos

x_train=np.random.uniform(xmin,xmax,n_train)
t_train=np.random.uniform(tmin,tmax,n_train)
tensor_train=np.column_stack((x_train,t_train))
tensor_train=tf.convert_to_tensor(tensor_train,dtype=tf.float32)

x_train0=np.random.uniform(xmin,xmax,size=n_train0)
t_train0=np.zeros(n_train0)
tensor_train0=np.column_stack((x_train0,t_train0))
tensor_train0=tf.convert_to_tensor(tensor_train0,dtype=tf.float32)

t = tf.convert_to_tensor(np.random.uniform(tmin,tmax,n_border),dtype=tf.float32)
tensor_border1 = tf.stack([ceros,t], axis=-1)
tensor_border2 = tf.stack([miles,t], axis=-1)

T00 = tf.transpose(T0(x_train0))


#@tf.function
def model_fit(N_STEPS):
    history = {'loss': [0.0], 'PL': [0.0], 'ZL': [0.0], 'BL': [0.0]}
    for step in range(0,N_STEPS+1):
        with tf.GradientTape(persistent=True) as tape:
            with tf.GradientTape(persistent=True) as tape2:
                tape2.watch(tensor_train)
                with tf.GradientTape(persistent=True) as tape3:
                    tape3.watch(tensor_train)
                    tape3.watch(tensor_train0)
                    tape3.watch(tensor_border1)
                    tape3.watch(tensor_border2)

                    TNN = model(tensor_train,training=True)
                    TNN0 = model(tensor_train0,training=True)
                    TNNborder1 = model(tensor_border1,training=True)
                    TNNborder2 = model(tensor_border2,training=True)

                partial_derivatives1 = tape3.gradient(TNN,tensor_train)
                partial_derivatives_x = partial_derivatives1[:, 0:1]  # Extraer componente

            partial_derivatives2 = tape2.gradient(partial_derivatives_x, tensor_train)
            partial_loss = model.compiled_loss(partial_derivatives1[:,1]+v_tensor*partial_derivatives1[:,0], alpha_tensor*partial_derivatives2[:,0]-R*(TNN-Tinf))
            zero_loss = model.compiled_loss(TNN0, T00)
            border_loss = model.compiled_loss(TNNborder1,TNNborder2)
            loss=tf.cast(partial_loss, dtype=tf.float32)+tf.cast(zero_loss, dtype=tf.float32)+tf.cast(border_loss, dtype=tf.float32)

        gradients=tape.gradient(loss,model.trainable_weights)
        model.optimizer.apply_gradients(zip(gradients, model.trainable_weights))

        if step % log_each == 0:
            metrics= {m.name: m.result() for m in model.metrics}
            metrics['PL']= partial_loss.numpy()
            metrics['ZL']=zero_loss.numpy()
            metrics['BL']=border_loss.numpy()
            print("step=",step,metrics)
            for key in history.keys():
                history[key].append(metrics[key])
    return history
    '''
    if step % log_each == 0:
      print(f'{step}/{N_STEPS} partial_loss {partial_loss:.5f} zero_loss {zero_loss:.5f}  border_loss {border_loss:.5f}')
    '''

history=model_fit(N_STEPS)

"""# Evolución de las pérdidas

"""

print(history.keys())
key='ZL'

steps=np.linspace(0,int(N_STEPS/log_each)+2,int(N_STEPS/log_each)+2)
print(steps.shape,np.array(history[key]).shape)
plt.scatter(steps,np.log(history[key]),label=key)
plt.xlabel("steps")
plt.ylabel('log scale')
plt.legend()
plt.show()

"""# Funcion t concreto"""

t= np.random.uniform(tmin,tmax)
c=1

# Crea un bucle para cada valor de tiempo

puntos=2000

x = np.linspace(xmin,xmax,puntos)

  # Evalúa la función real y la salida de la red neuronal en la malla de puntos
t_array=tf.ones(puntos)
t_array=t_array*t

tensor=np.column_stack((x,t_array))
Z_real=T_real(x,t)
Z_nn=model(tensor)

# Grafica las funciones

plt.figure(figsize=(8, 6))
plt.scatter(x, Z_real, label='Real',color='deepskyblue')
plt.scatter(x, Z_nn, label='Red Neuronal',color='coral')
plt.xlabel('x')
plt.ylabel('F(x)')
plt.title(f'Comparación en t={t:.2f}')
plt.legend()
plt.show()

"""# GIF

"""

t_values = np.linspace(tmin,tmax, 150)  # Valores de tiempo en los que quieres evaluar la función

# Crea un bucle para cada valor de tiempo
images = []
for t in t_values:
    # Define la malla de puntos (x, t)
    x = np.linspace(xmin, xmax, 200)
    X, T = np.meshgrid(x, [t])

    # Evalúa la función real y la salida de la red neuronal en la malla de puntos
    t_array=np.zeros(50)
    for i in range (0,50):
        t_array[i]=t
    tensor=np.column_stack((x,t_array))

    Z_real=T_real(x,t_array)
    Z_nn=model(tensor)

    # Grafica las funciones
    plt.figure(figsize=(8, 6))
    plt.plot(x, Z_real, label='Real',color='deepskyblue')
    plt.plot(x, Z_nn, label='Red Neuronal',color='coral')
    plt.xlabel('x')
    plt.ylabel('F(x)')
    plt.ylim(-1,1.5)
    plt.title(f'Comparación en t={t:.2f}')
    plt.legend(loc='upper left')

    # Guarda la imagen como un archivo temporal
    filename = f'comparison_t_{t:.2f}.png'
    plt.savefig(filename)
    images.append(imageio.imread(filename))
    plt.close()

# Combina las imágenes en un GIF
imageio.mimsave('./escalon.gif', images)

